# Generated by Django 4.2.1 on 2023-06-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('size', models.IntegerField()),
                ('image', models.ImageField(upload_to='comps/')),
            ],
        ),
    ]
