# Generated by Django 4.2.1 on 2023-06-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('year', models.CharField(max_length=255)),
                ('madel', models.CharField(max_length=255)),
                ('probeg', models.IntegerField()),
            ],
        ),
    ]
